class Exeption_sub(Exception):
    print('Error 1')


class Exception_sub_sub(Exeption_sub):
    print('Error 2')


